# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: 'en-US'
tone_instructions: give formal and direct reviews with no humour and any other distracting text, only the necessary
reviews:
    profile: 'assertive'
    request_changes_workflow: true
    auto_review:
        enabled: true
    poem: false
    high_level_summary: true
    suggested_labels: true
    auto_apply_labels: true
    labeling_instructions:
        - label: '⏱️ <10 Min Review'
          instructions: >-
              Apply this label if the pull request modifies fewer than 100 lines.

        - label: '⏱️ 10-30 Min Review'
          instructions: >-
              Apply this label if the pull request modifies between 100 and 500.

        - label: '⏱️ 30-60 Min Review'
          instructions: >-
              Apply this label if the pull request modifies between 500 and 1000 lines.

        - label: '⏱️ 60+ Min Review'
          instructions: >-
              Apply this label if the pull request changes more than 1000 lines.
    path_instructions:
        - path: './'
          instructions: |
              Use camelCase and plural naming for module folders (e.g. users, internalReports).
              Follow the standardized folder structure MUST allow only those folders:
                - actions/
                - controller/
                - config/
                - includes/
                - locales/
                - helpers/
                - install/
                - models/
                - scripts/
                - test/
                - tests/
                - views/
                - .github
                - .github
                - .github
                - .github

        - path: '*.php'
          instructions: |
              All PHP code should follow PHP PSR-12 standards
              All PHP code should follow DRY and SOLID principles
              All PHP code should follow best practices

        - path: '/controller/*.php'
          instructions: |
              Files here MUST contain only controller logic and we SHOULD avoid add business logic here, but rather delegate it to services

        - path: '/actions/*.php'
          instructions: |
              Files here MUST contain only controller logic and we SHOULD avoid add business logic here, but rather delegate it to services
              
        - path: 'manifest.php'
          instructions: |
              All the extension definition should be done here
              All ACL roles must be defined here
              All DependencyInjection ServiceProviders should be declared here
chat:
    auto_reply: true
